name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "in-review"]
assignees:
  - glharper
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.48.0 (Latest, Default)
        - 1.47.0
        - 1.46.0
        - 1.45.0
        - 1.44.1
        - 1.44.0
        - 1.43.1
        - 1.43.0
        - 1.42.0
        - 1.41.0
        - Older
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser/platform are you seeing the problem on?
      multiple: true
      options:
        - Node
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - React
        - React Native
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging).
      render: shell
