// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

import { AudioOutputStream } from "./Audio/AudioOutputStream";

/**
 * Defines contents of received message/events.
 * @class ActivityReceivedEventArgs
 */
export class ActivityReceivedEventArgs {
    private privActivity: string;
    private privAudioStream: AudioOutputStream;

    /**
     * Creates and initializes an instance of this class.
     * @constructor
     * @param {string} activity - The activity..
     */
    public constructor(activity: string, audioStream?: AudioOutputStream) {
        this.privActivity = activity;
        this.privAudioStream = audioStream;
    }

    /**
     * Gets the received activity
     * @member ActivityReceivedEventArgs.prototype.activity
     * @function
     * @public
     * @returns {string} the received activity.
     */
    public get activity(): string {
        return this.privActivity;
    }

    /**
     * Gets the received audio stream for the given activity.
     * @member ActivityReceivedEventArgs.prototype.audioStream
     * @function
     * @public
     * @returns {AudioOutputStream} the TTS audio stream generated by the activity.
     */
    public get audioStream(): AudioOutputStream {
        return this.privAudioStream;
    }
}
